import type { Metadata } from "next";
import { SITE_URL, OG_IMAGE_URL, OG_IMAGE_SQUARE_URL } from "./site";

export const META = {
  title: "Satwik Kanhere | Full-Stack SDE | Java Spring Boot React Next.js",
  description:
    "Satwik Kanhere is a Full-Stack Software Development Engineer 1 at WizCommerce — Java, Spring Boot, Hibernate, React.js, Next.js, and TypeScript. CRM, PIM, Ag-Grid SSRM, payments, CDN. B.Tech CSE Chitkara (9.41 CGPA). Hire: satwikkanhere2003@gmail.com · +91 6284486063 · satwikkanhere.dev/about",
  keywords: [
    // === Name variations (CRITICAL for ranking) ===
    "Satwik Kanhere",
    "Satvik Kanhere",
    "Satwik",
    "Satvik",
    "satwikkanhere",
    "Satwik K",
    "Satvik K",
    "Satwik Kanhere developer",
    "Satwik Kanhere portfolio",
    "Satwik Kanhere software engineer",
    "Satwik Kanhere WizCommerce",
    "Satwik Kanhere resume",
    "Satwik Kanhere LinkedIn",
    "Satwik Kanhere GitHub",
    "Satvik Kanhere developer",
    "Satvik Kanhere portfolio",
    "Satwik software developer",
    "Satwik developer India",
    "Satwik SDE",
    "Satwik full stack developer",
    "who is Satwik Kanhere",

    // === Role & title keywords ===
    "Software Development Engineer",
    "Software Developer",
    "SDE",
    "SDE 1",
    "Full Stack Developer",
    "Full-Stack Developer",
    "Frontend Developer",
    "Backend Developer",
    "Web Developer",
    "Software Engineer",
    "React Developer",
    "Next.js Developer",
    "Node.js Developer",
    "TypeScript Developer",
    "JavaScript Developer",
    "Java Developer",
    "Spring Boot Developer",
    "Hibernate Developer",
    "JPA Developer",
    "MERN Stack Developer",
    "Full Stack Java Developer",

    // === Technology keywords ===
    "React.js",
    "Next.js",
    "Node.js",
    "Express.js",
    "Spring Boot",
    "Hibernate",
    "JPA",
    "TypeScript",
    "JavaScript",
    "Java",
    "PostgreSQL",
    "MongoDB",
    "Prisma",
    "Kafka",
    "Ag-Grid",
    "TailwindCSS",
    "REST API",
    "WebSocket",
    "GraphQL",
    "Redis",
    "Docker",
    "AWS",
    "CI/CD",
    "Git",
    "GitHub",

    // === Company & education keywords ===
    "WizCommerce",
    "WizCommerce developer",
    "Infosys developer",
    "Infosys intern",
    "Chitkara University",
    "Chitkara University CSE",
    "Chitkara University developer",

    // === Location keywords ===
    "Developer India",
    "Developer Chandigarh",
    "Developer Gurugram",
    "Software Engineer India",
    "Hire developer India",
    "Remote developer India",
    "Best developer India",
    "Top developer Chandigarh",

    // === Project & achievement keywords ===
    "PIM System developer",
    "Product Information Management",
    "Enterprise software developer",
    "Springer published developer",
    "Blockchain IoT Healthcare",
    "Assembly design studio",
    "Flux AI IDE",
    "Ag-Grid SSRM",
    "eBizCharge Finix CyberSource",
    "Apple assistive technology",
    "100000 SKUs PIM",
    "120 enterprise clients",

    // === Hiring intent keywords ===
    "Hire Full Stack Developer",
    "Hire React Developer India",
    "Hire Next.js Developer",
    "Hire TypeScript Developer",
    "Hire Frontend Developer India",
    "Hire Node.js Developer",
    "Freelance developer India",
    "Contract React developer",
    "Contract frontend engineer",
    "Software engineer for hire India",
    "Best software developer portfolio",
    "Top software engineer portfolio",
    "Developer portfolio website",
    "satwikkanhere.dev",

    // === Long-tail search phrases ===
    "Satwik Kanhere software development engineer",
    "Satwik Kanhere React Next.js TypeScript",
    "Satwik Kanhere Chitkara University",
    "Satwik Kanhere Infosys",
    "Satwik Kanhere Gurugram",
    "Satwik Kanhere Chandigarh developer",
    "frontend engineer WizCommerce",
    "Ag-Grid SSRM developer India",
    "PIM developer React TypeScript",
    "enterprise frontend developer India",
  ],
  siteName: "Satwik Kanhere - Software Development Engineer",
  ogTitle: "Satwik Kanhere | Software Development Engineer at WizCommerce",
  ogDescription:
    "Full-stack SDE 1 at WizCommerce | Java · Spring Boot · Hibernate · React · Next.js · TypeScript | Assembly & Flux | Apple assistive tech | 9.41 CGPA",
  twitterTitle: "Satwik Kanhere | Full-Stack Software Development Engineer",
  twitterDescription:
    "Full-stack SDE 1 at WizCommerce | Java/Spring Boot/Hibernate + React/Next.js/TypeScript | Ag-Grid · payments · CDN",
  author: "Satwik Kanhere",
  authorUrl: "https://linkedin.com/in/satwikkanhere0730",
  twitterHandle: "@satwikkanhere",
  category: "Technology",
  classification: "Software Development Portfolio",
} as const;

export function getMetadata(): Metadata {
  return {
    title: META.title,
    description: META.description,
    keywords: [...META.keywords],
    authors: [
      { name: "Satwik Kanhere", url: META.authorUrl },
      { name: "Satvik Kanhere", url: META.authorUrl },
    ],
    creator: META.author,
    publisher: META.author,
    robots: {
      index: true,
      follow: true,
      nocache: false,
      googleBot: {
        index: true,
        follow: true,
        noimageindex: false,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    alternates: {
      canonical: SITE_URL,
      languages: {
        "en-US": SITE_URL,
        "en-IN": SITE_URL,
        "en": SITE_URL,
      },
    },
    openGraph: {
      type: "profile",
      locale: "en_US",
      url: SITE_URL,
      siteName: META.siteName,
      title: META.ogTitle,
      description: META.ogDescription,
      images: [
        {
          url: OG_IMAGE_URL,
          secureUrl: OG_IMAGE_URL,
          width: 1200,
          height: 630,
          alt: "Satwik Kanhere - Software Development Engineer Portfolio",
          type: "image/jpeg",
        },
        {
          url: OG_IMAGE_SQUARE_URL,
          width: 600,
          height: 600,
          alt: "Satwik Kanhere - SDE at WizCommerce",
          type: "image/jpeg",
        },
      ],
      firstName: "Satwik",
      lastName: "Kanhere",
      username: "satwikkanhere",
      gender: "male",
    },
    twitter: {
      card: "summary_large_image",
      site: META.twitterHandle,
      creator: META.twitterHandle,
      title: META.twitterTitle,
      description: META.twitterDescription,
      images: {
        url: OG_IMAGE_URL,
        alt: "Satwik Kanhere - Software Development Engineer",
      },
    },
    appLinks: {
      web: {
        url: SITE_URL,
        should_fallback: true,
      },
    },
    category: META.category,
    classification: META.classification,
    verification: {
      /** Matches <meta name="google-site-verification"> in root layout */
      google: "bJZ1VDoftPbrcFtzdlTF5ffCR0lLUjqOJH6IRxw8qQw",
    },
    other: {
      "linkedin:owner": "satwikkanhere0730",
      "pinterest-rich-pin": "true",
      "article:author": META.author,
      "article:published_time": "2025-01-01T00:00:00Z",
      "article:modified_time": new Date().toISOString(),
      "contact:email": "satwikkanhere2003@gmail.com",
      "contact:phone": "+91-6284486063",
      "geo.region": "IN-CH",
      "geo.placename": "Chandigarh",
      "geo.position": "30.7333;76.7794",
      ICBM: "30.7333, 76.7794",
      language: "English",
      "revisit-after": "3 days",
      rating: "General",
      distribution: "Global",
      coverage: "Worldwide",
      "mobile-web-app-capable": "yes",
      "apple-mobile-web-app-capable": "yes",
      "apple-mobile-web-app-status-bar-style": "black-translucent",
      "apple-mobile-web-app-title": "Satwik Kanhere",
      "msapplication-TileColor": "#4928fd",
      "msapplication-config": "/browserconfig.xml",
      "dc.title": "Satwik Kanhere - Software Development Engineer",
      "dc.creator": "Satwik Kanhere",
      "dc.subject": "Software Development, Full-Stack Engineering, React.js, Node.js",
      "dc.description": META.description,
      "dc.language": "en",
    },
  };
}
